services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_sreality
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:3000"
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"