services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_sreality
    ports:
      - "5432:5432"
    volumes:
      - ./database/structure.sql:/docker-entrypoint-initdb.d/00_structure.sql
      - ./database/flat_insert.sql:/docker-entrypoint-initdb.d/01_flat_insert.sql
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - database
  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_started
    ports:
      - "5000:5000"